homeassistant:
  # Name of the location where Home Assistant is running
  name: !env_var HASS_NAME
  # Location required to calculate the time the sun rises and sets
  latitude: !env_var HASS_LATITUDE
  longitude: !env_var HASS_LONGITUDE
  # Impacts weather/sunrise data
  elevation: !env_var HASS_ELEVATION
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  customize: !include customize.yaml

logger:
  default: "warn"

# Enables the frontend
frontend:

config:

http:
  api_password: !env_var HASS_HTTP_API_PASSWORD


# Checks for available updates
updater:

# Discover some devices automatically
# discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

recorder:
  db_url: !env_var HASS_DB_URL
  purge_interval: 2
  purge_keep_days: 60

# View all events in a logbook
logbook:

# Track the sun
sun:

cloud: !include conf.d/cloud.yaml
mqtt: !include conf.d/mqtt.yaml
sensor: !include_dir_merge_list conf.d/sensor/
group: !include_dir_named conf.d/group/
zone: !include_dir_list conf.d/zone/
automation old: !include_dir_merge_list conf.d/automation/
automation: !include automations.yaml
scene: !include_dir_list conf.d/scene/

device_tracker:
  platform: owntracks
  max_gps_accuracy: 200

notify:
  name: pushover
  platform: pushover
  api_key: !env_var HASS_PUSHOVER_API_KEY
  user_key: !env_var HASS_PUSHOVER_USER_KEY

ifttt:
  key: !env_var HASS_IFTTT_KEY

tradfri:
  host: !env_var HASS_TRADFRI_HOST

ios:

media_player:
  - platform: webostv
    host: !env_var HASS_WEBOSTV_HOST
    name: TV
    customize:
      sources:
        - livetv
        - youtube
        - netflix
        - hdmi1
        - hdmi2
        - hdmi3
  - platform: onkyo
    host: !env_var HASS_ONKYO_HOST
    name: Receiver
    sources:
      tv: TV
      strm-box: Alexa
      network: Network
      bluetooth: Bluetooth
