- platform: mqtt
  state_topic: "things/bad0/getTemperature/res"
  name: "Bathroom"
  unit_of_measurement: "°C"
  value_template: "{{ value_json.getTemperature | round(2) }}"
- platform: mqtt
  state_topic: "things/bad0/getHumidity/res"
  name: "Bathroom"
  unit_of_measurement: "%"
  value_template: "{{ value_json.getHumidity | round(2) }}"
