- platform: mqtt
  state_topic: "things/desk/getTemperature/res"
  name: "Desk"
  unit_of_measurement: "°C"
  value_template: "{{ value_json.getTemperature | round(2) }}"
- platform: mqtt
  state_topic: "things/desk/getHumidity/res"
  name: "Desk"
  unit_of_measurement: "%"
  value_template: "{{ value_json.getHumidity | round(2) }}"
- platform: mqtt
  state_topic: "things/desk/getLuminosity/res"
  name: "Desk"
  unit_of_measurement: "lm"
  value_template: "{{ value_json.getLuminosity | round(2) }}"
- platform: mqtt
  state_topic: "things/switch_desk_stat/getState/res"
  name: "Desk (Power)"
  unit_of_measurement: "W"
  value_template: "{% if 'POWER' in value_json.getState %}{{ value_json.getState.POWER | round(0) }}{% else %}{{ states('sensor.desk_power') }}{% endif %}"
