- platform: mqtt
  state_topic: "things/heater_kitchen/getTemperature/res"
  name: "Heater Kitchen (actual)"
  unit_of_measurement: "°C"
  value_template: "{{ value_json.getTemperature | round(2) }}"
- platform: mqtt
  state_topic: "things/heater_kitchen/getMode/res"
  name: "Heater Kitchen (mode)"
  unit_of_measurement: ""
  value_template: "{{ value_json.getMode }}"
- platform: mqtt
  state_topic: "things/heater_kitchen/getState/res"
  name: "Heater Kitchen (set)"
  unit_of_measurement: "°C"
  value_template: "{% if 'SET_TEMPERATURE' in value_json.getState %}{{ value_json.getState.SET_TEMPERATURE | round(2) }}{% else %}{{ states('sensor.heater_bed_set') }}{% endif %}"
- platform: mqtt
  state_topic: "things/heater_kitchen/getState/res"
  name: "Heater Kitchen (valve)"
  unit_of_measurement: "%"
  value_template: "{% if 'VALVE_STATE' in value_json.getState %}{{ value_json.getState.VALVE_STATE | round(0) }}{% else %}{{ states('sensor.heater_bed_valve') }}{% endif %}"
- platform: mqtt
  state_topic: "things/heater_kitchen/getState/res"
  name: "Heater Kitchen (battery)"
  unit_of_measurement: "V"
  value_template: "{% if 'BATTERY_STATE' in value_json.getState %}{{ value_json.getState.BATTERY_STATE | round(1) }}{% else %}{{ states('sensor.heater_bed_battery') }}{% endif %}"
