- platform: mqtt
  state_topic: 'things/dracoL/waterLevel/res'
  name: Draco L Water Level
  unit_of_measurement: s
  value_template: '{{ value | int }}'
- platform: mqtt
  state_topic: 'things/dracoL/moisture/res'
  name: Draco L Moisture
  unit_of_measurement: '%'
  value_template: '{{ value | float }}'
