- platform: mqtt
  name: "Desk"
  command_topic: "things/switch_desk_power/setPower/req"
  payload_on: "{\"setPower\": true}"
  payload_off: "{\"setPower\": false}"
  state_topic: "things/switch_desk_power/setPower/res"
  value_template: "{% if value_json.setPower %}{\"setPower\": true}{% else %}{\"setPower\": false}{% endif %}"
