- platform: mqtt
  name: "Kodi"
  command_topic: "things/kodi/setPower/req"
  payload_on: "{\"setPower\": true}"
  payload_off: "{\"setPower\": false}"
  state_topic: "things/kodi/setPower/res"
  value_template: "{% if value_json.setPower %}{\"setPower\": true}{% else %}{\"setPower\": false}{% endif %}"
